name: Clean, build, test and package

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WALLET_1_MNEM:  ${{ secrets.WALLET_1_MNEM }}
  WALLET_2_MNEM:  ${{ secrets.WALLET_2_MNEM }}
  WALLET_1_PASS:  ${{ secrets.WALLET_1_PASS }}
  WALLET_2_PASS:  ${{ secrets.WALLET_2_PASS }}

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions/setup-java@v1.4.2
        with:
          java-version: '11.0.8'
      - run: sbt coverage test coverageReport
        env:
          BASE_URL: http://cardano-wallet-testnet.iog.solutions:8090/v2/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: target/scala-2.13/scoverage-report
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        uses: actions/setup-java@v1.4.2
        with:
            java-version: '11.0.8'
      - run: sbt publish

